version: "3"

networks:
  tfk_network:

services:

  traefik:
    restart: always
    networks:
      - tfk_network
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/tfk.log"
      - "--accesslog=true"
      - "--accesslog.filePath=/var/log/tfk_access.log"
      - "--accesslog.filters.minduration=10ms"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=lesherwesley@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=./acme/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    # labels:
    #   - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    #   - "traefik.http.routers.dashboard.service=api@internal"
    #   - "traefik.http.routers.dashboard.middlewares=auth"
    #   - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
    #   - traefik.http.services.dashboard.loadbalancer.server.port=8080
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./acme:/acme"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/log:/var/log"
    
